version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SA_PATH=/run/secrets/firebase_sa
      - FIREBASE_BUCKET=${FIREBASE_BUCKET}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - VECTOR_BACKEND=faiss
      - MAX_WORKERS=6
    secrets:
      - firebase_sa
secrets:
  firebase_sa:
    file: ./service-account.json